#How long between each broadcast message, in seconds.
#Set to 15 to see all announcements. I recommend about a 60 second interval between announcements.
interval: 15

announcements:
  - '&6&lIMPULSE &8&l- &eThank you for downloading &6Impulse'
  - '%nl%&eThis is an example %nl%of multi line broadcasts%nl%'
  - '&6&lIMPULSE &8&l- &eOnce you update the config make sure to reload the plugin by doing &6/impulse reload'
  - '&6&lCONFIG &8&l- &eChange these messages in the &6config.yml'

reload-message: '&eReloaded the config'